name: eosv2_ci

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 9 * * *'
  push:
    branches: [ "v2" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "v2" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
 docker_clean:
  runs-on: ubuntu-latest

  steps:
   - name: clean docker	
     run: |
      sudo docker rm `sudo docker ps --all | grep -i -v container | awk '{print $$1}'`
      sudo docker rmi `sudo docker images --all | grep -i -v container | awk '{print $$3}'`

 docker_show:
  runs-on: ubuntu-latest
  steps:
   - name: show all
     run: |
      sudo docker ps --all
      sudo docker images --all

 build:
   runs-on: ubuntu-latest
   steps:
   - name: build all
     run: |
      sudo docker build - < ../../dockerfilev2 \
      -t sroy14/eos:v2 > build.out 2>&1
      sudo docker run sroy14/eos:v2 sh -c \
      "curl -o fid_3_5_22.o2 https://isospin.roam.utk.edu/public_data/eos_tables/du21/fid_3_5_22.o2 && mpirun --allow-run-as-root -np 1 ./eos_nuclei -load fid_3_5_22.o2 -point-nuclei 0.16 0.4 1.0" \
      > test_alpha2.out 2>&1

 push:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: push the image
     run: sudo docker push sroy14/eos:v2
