name: eosv2_ci

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 9 * * *'
  push:
    branches: [ "v2" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "v2" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: nostrad1/utk-eos

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: build all
     run: sudo docker pull nostrad1/utk-eos:v2
       
 test:
  runs-on: ubuntu-latest
  needs: build
  steps: 
   - name: test code
     run: sudo docker run nostrad1/utk-eos:v2 sh -c \
	 "mpirun --allow-run-as-root -np 1 ./eos_nuclei -load data/fid_3_5_22.o2 -point-nuclei 0.16 0.4 1.0" \

 push:
   runs-on: ubuntu-latest
   needs: [build, test]
   steps:
   - name: push the image
     run: sudo docker push nostrad1/utk-eos:v2
