name: ci

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 9 * * *'
  push:
    branches: [ "v2" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "v2" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --tag eosv2 - < dockerfilev2
        env:
          DOCKER_CLI_ACI: 1

  test:
    runs-on: eosv2
    container: utk_eos
    steps:
      - name: Run tests
        run: bash test.sh

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --tag sroy14/eosv2:latest -f dockerfilev2 .
        env:
          DOCKER_CLI_ACI: 1

